### ISSUE TITLE
add a check for isGonadSaved for a certain barcode type

### ISSUE THREAD

**Issue by bdschwartzkopf** [kstierhoff/estimATM#102]
Hoping to add code to make sure that individuals with a barcode that indicates a gonad was saved actually says in the database that a gonad was saved. Here is the text for checktrawls and the code:

This barcode type indicates that isGonadSaved should be "Y" so please confirm. 

histo.check <- specimens %>% 
  filter(startsWith(as.character(individual_ID), "0"),
         isGonadSaved=="N")

**Comment by kstierhoff** [comment]
Implemented this functionality and tested on data in SQL Server for 2307RL. Will continue testing and improving during 2407RL.
