### ISSUE TITLE
Updates to Check Transects

### ISSUE THREAD

**Issue by alicebeittel** [kstierhoff/estimATM#107]
Two code improvement requests! 
1. Looks like check transects will only take waypoints to the tenths place. For example, 045C around the channel islands has waypoints 045.1C - 045.11C, but the .11 and .10 waypoints will be converted to 045.1 after running checkTransects which means the graphs of the channel islands will show a line through the island instead of around the island like intended (yellow highlight) . Request: adjust code to allow for waypoints into the hundredths place.

2. Edit code to allow for multiple individual segments of a transect. Example: one line to the western side of San Clemente and one line on the eastern side of San Clemente (red circle).

![image](https://github.com/kstierhoff/estimATM/assets/112714266/d2a35c04-ab76-400f-9fb9-73053b156ec8)

**Comment by kstierhoff** [comment]
For transect numbering, inshore waypoint should be XXX.1, offshore point should be XXX.2, in between should be XXX.101, XXX.102...XXX.10n, then XXX.2. What's the rationale for multiple segments? To facilitate regional sampling planning?

**Comment by alicebeittel** [comment]
The multiple segments is just for that one line around san clemente, it doesn't make sense to me to have the line drawn all the way around the island since there are two transects bordering the island already. It's a nice natural break of where we would likely already break the line for regional sampling patterns.

**Comment by kstierhoff** [comment]
Good copy. Given the few number of transects involved, I'm gonna downgrade the urgency of this one for now. But I'll keep the issue open.

**Comment by kstierhoff** [comment]
This is a rare occurrence and may not be worth addressing in the code for cruise planning purposes. We can recommend a transit route around the islands for the ship's consideration, and allow them to choose the best course. Closing this issue.
