### ISSUE TITLE
Clarify logic for calling sub-functions

### ISSUE THREAD

**Issue by jrenfree** [kstierhoff/estimATM#5]
Certain subfunctions are sourced by multiple scripts to complete specific tasks. The user decides if these subfunctions get sourced, with the logic (e.g., if statements) being located within those subfunctions themselves, making it less obvious on if that subfunction will be sourced from the main script.

For example, the beginning of get_nav_erddap.R begins with:
`if (get.nav) { ... }`

The variable get.nav is defined in reportSurvey_2207RL.Rmd, which then sources get_nav_erddap.R:
`get.nav <- T`
...
`source(here("Code/get_nav_erddap.R"))`

Therefore, when sourcing get_nav_erddap.R, it is not clear that the execution of that script is dependent on get.nav. Moreover, if the user wants to manually execute get_nav_erddap.R, they must first define the variable get.nav, which defeats the entire purpose of wanting to run the script in the first place.

This same type of logic might also be present in other subfunctions, such as process_NASC.R.

**Comment by kstierhoff** [comment]
I sense a little hostility in this issue...I'm gonna go ahead and close it.

Seriously though, get_nav_erddap.R is only called from within other .Rmd files and is not meant to be standalone. .Rmd files that source this script have get.nav defined at the top (or should), so I'm not sure the logic is flawed. A separate script or function should be created to get nav data from ERDDAP if desired.
