### ISSUE TITLE
Errors running plot_purseSeine_2207RL.R

### ISSUE THREAD

**Issue by jrenfree** [kstierhoff/estimATM#7]
I get a number of errors when running this script. Some of the figures do get made, although I'm not sure correctly. For example, the figure 'fig_seine_proportion_set_wt_Carnage.png' appears to plot trawl proportions for Lasker trawls.

It also appears that there are references to files that I either may not have or which use hard-coded paths, such as:
- 'lm_tracks_20220825.gpx'
- 'C:/KLS/CODE/Github/estimATM/2207RL/Data/Nav/nav_data.Rdata'
- C:/KLS/CODE/Github/estimATM/2207RL/Data/Map/basemap.Rdata

**Comment by kstierhoff** [comment]
I believe this has been resolved in later reports by using a generic purseSeine plotting routine. Reopen if not.
