### ISSUE TITLE
add duplicated DNA to checkTrawls

### ISSUE THREAD

**Issue by bdschwartzkopf** [kstierhoff/estimATM#94]
It would be good to add in a check to see if there are duplicated DNA tray and vial combinations. Here is basic code I used to check this. 

dna.only <- specimens %>%
  mutate(unqdna=paste(specimens$DNAtrayNumber,specimens$DNAvialNumber)) %>%
  filter(!is.na(DNAtrayNumber))

t <- as.data.frame(table(dna.only$unqdna))
tt <- subset(t, Freq==2)

dupid <- tt$Var1

dd <- dna.only[dna.only$unqdna %in% dupid,]

**Comment by bdschwartzkopf** [comment]
I just realized this wasn't the exact implement. This is a great addition, but the code I had used combines the DNA tray and vial number into a unique ID, and then looks for duplicates. This would be similar to what the check duplicated barcode ID's would look like.

**Comment by kstierhoff** [comment]
Implemented the duplicate tray code and tested with the database.
